[fs]
artifacts = "artifacts"
documentation = "documentation"
presentation = "slides"
report = "report"
common-images = "images"


# Either asciidoc, beamer, markdown or purelatex

[compilation]
documentation = false
presentation = true
report = true
purelatex = false

[common]
author = ["Constantin \\textsc{Gierczak-Galle}" ]
affiliation = ["ENS Paris"]

[common.pandoc-args]
listings = false
highlight-style = "pygments"

[common.ressoures]
references = "references.bib"

[utilitaries]
asciidoc = "asciidoc"
bibtex = "bibtex"
latex = "xelatex"
pandoc = "pandoc"

[report]
name = "report"
latex-args = ["\\usetikzlibrary{chains,decorations.pathreplacing}"]
listings = true
title = "Arlustre"
latex-packages = ["tikz"]
references = false
references-file = "references.bib"
template = "./template.latex"
numbersections = true
images = false
images-path = "images"

[report.yaml-args]
toc = true

[slides.pandoc-args]
listings = true
slide-level = 2

[slides]
name = "test"

[documentation]
name = "significant documentation"

[report.pandoc-args]
dimension = "a4paper"
margin = "3cm"
